command might have arguments don't use quotes

diff --git a/templates/certbot-deploy.sh.j2 b/templates/certbot-deploy.sh.j2
--- a/templates/certbot-deploy.sh.j2
+++ b/templates/certbot-deploy.sh.j2
@@ -63,6 +63,6 @@ if [ "$SERVICE" != "" ]; then
 fi
 
 if [ "$COMMAND" != "" ] ; then
-	"${COMMAND}" || die "${COMMAND} failed to run"
+	${COMMAND} || die "${COMMAND} failed to run"
 fi
 exit 0
